name: Deploy to devops-02

on:
  push:
    branches:
      - main

concurrency:
  group: devops-02-deployment
  cancel-in-progress: false

jobs:
  validate:
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Validate Docker Compose
        run: docker compose config

      - name: Prepare Ansible deployment files
        run: |
          cp compose.yaml ansible/roles/monitoring/files/compose.yaml
          cp Dockerfile ansible/roles/monitoring/files/Dockerfile
          cp index.html ansible/roles/monitoring/files/index.html

      - name: Debug Ansible files
        run: |
          pwd
          find ansible -maxdepth 3 -type f | sort
          echo "----- inventory -----"
          cat ansible/inventories/test.ini

      - name: Validate Ansible syntax
        working-directory: ansible
        run: |
          ansible-playbook \
            -i inventories/test.ini \
            deploy-test-stack.yml \
            --syntax-check

      - name: Verify Ansible connectivity
        working-directory: ansible
        run: ansible test -i -i inventories/test.ini -m ping

  deploy:
    needs: validate
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Prepare Ansible deployment files
        run: |
          cp compose.yaml ansible/roles/monitoring/files/compose.yaml
          cp Dockerfile ansible/roles/monitoring/files/Dockerfile
          cp index.html ansible/roles/monitoring/files/index.html

      - name: Deploy with Ansible
        working-directory: ansible
        run: |
          ansible-playbook \
            -i inventories/test.ini \
            deploy-test-stack.yml

      - name: Verify web application
        run: |
          curl --fail --retry 10 --retry-delay 3 \
            http://10.0.0.129:8080/

      - name: Verify Prometheus
        run: |
          curl --fail --retry 10 --retry-delay 3 \
            http://10.0.0.129:9090/-/healthy

      - name: Verify Loki
        run: |
          curl --fail --retry 10 --retry-delay 3 \
            http://10.0.0.129:3100/ready
